### ISSUE TITLE
Why toggle dark/light mode on click'?

### ISSUE THREAD

**Issue by davesnx** [scotato/sleeper#2]
Hey @scotato 

Love the idea, why do you want people to change dark mode to light mode and vice-versa on click? It would make more sense to have a toggle somewhere or detect user preferences.

Thanks! :D

**Comment by scotato** [comment]
Hey @davesnx 

Absolutely, I wanted to put the dark mode toggle on a settings screen pre-launch but decided to launch without it just to get it online faster.

I'll get this added in the next release, thanks for your feedback!

**Comment by davesnx** [comment]
👍 Thanks
